### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by ajmeese7** [ChrisVilches/Wobbly-Matrix#1]
Hey there Chris, this is a super cool project! I was wondering if you would consider enabling GitHub pages for the repository so visitors can see the code in action without needing to clone the repo and run it locally.

Cheers!

**Comment by ChrisVilches** [comment]
@ajmeese7 It's possible, but it's a bit buggy as of now so I'd like to fix it a bit first 😄

**Comment by ajmeese7** [comment]
Sounds good! If you could let me know when you do I'd appreciate it!

**Comment by ChrisVilches** [comment]
@ajmeese7 

- Refactored
- Algorithm fixed (10 times better and more realistic!)
- Page created and deployed
- Migrated from Javascript to Typescript

https://wobbly-matrix.netlify.app/

I still haven't created a configuration UI form so it has to be configured from the source code (I will soon update the readme file to explain how to do the setup/build, etc.).

But now the wobbling works even with aggressive mouse movements (before, it got really bugged). I feel it's 100% working the way I first intended.

**Comment by ajmeese7** [comment]
Looks awesome, great job! Closing this out now, thanks.
